name: JSS_Scratch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py37_0
  - cpuonly=1.0=0
  - freetype=2.10.2=h5ab3b9f_0
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_1
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.0=py37hfd86e86_0
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pcre=8.44=he6710b0_0
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.2.2=py37_0
  - python=3.7.7=hcff3b4d_5
  - pytorch=1.6.0=py3.7_cpu_0
  - readline=8.0=h7b6447c_0
  - setuptools=49.6.0=py37_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - swig=3.0.12=h38cdd7d_3
  - tk=8.6.10=hbc83047_0
  - torchvision=0.7.0=py37_cpu
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - aiohttp==3.6.2
    - aioredis==1.3.1
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - attrs==20.1.0
    - beautifulsoup4==4.9.1
    - blessings==1.7
    - box2d-py==2.3.8
    - cachetools==4.1.1
    - cffi==1.14.2
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.3.0
    - colorama==0.4.3
    - colorful==0.5.4
    - cython==0.29.21
    - filelock==3.0.12
    - future==0.18.2
    - glfw==1.12.0
    - google==3.0.0
    - google-api-core==1.22.1
    - google-auth==1.20.1
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - grpcio==1.31.0
    - gym==0.17.2
    - hiredis==1.1.0
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==1.7.0
    - joblib==0.16.0
    - jsonschema==3.2.0
    - lockfile==0.12.2
    - msgpack==1.0.0
    - multidict==4.7.6
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.10
    - opencensus-context==0.1.1
    - opencv-python==4.4.0.42
    - pandas==1.1.1
    - plotly==4.9.0
    - prometheus-client==0.8.0
    - protobuf==3.13.0
    - psutil==5.7.2
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyglet==1.5.0
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - ray==0.8.7
    - redis==3.4.1
    - requests==2.24.0
    - retrying==1.3.3
    - rsa==4.6
    - scipy==1.5.2
    - soupsieve==2.0.1
    - tabulate==0.8.7
    - tensorboardx==2.1
    - typing-extensions==3.7.4.3
    - urllib3==1.25.10
    - yarl==1.5.1
    - zipp==3.1.0
prefix: /home/local/IWAS/pierre/anaconda3/envs/JSS_Scratch

